local   all             all                      trust
hostssl all             all             127.0.0.1/32            cert
hostssl all             all             ::1/128                 cert
hostssl all             all             0.0.0.0/0               cert
hostssl all             all             ::/0                    cert
hostssl all             all             172.18.0.1/32           cert

