name: CLA
on:
  pull_request_target:
    types: [opened, synchronize]
  issue_comment:
    types: [created]
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write
jobs:
  cla:
    name: CLA Assistant
    if: |
      github.event_name == 'pull_request_target' ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request != null &&
       contains(github.event.comment.body, 'recheck'))
    runs-on: ubuntu-latest
    steps:
      - uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT_TOKEN }}
        with:
          path-to-signatures: signatures/cla.json
          path-to-document: https://github.com/hierarkey/hierarkey/blob/main/CLA.md
          branch: cla-signatures
          allowlist: jaytaph,dependabot[bot]
